name: Validate PR
on: [pull_request]

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: Borales/actions-yarn@master
      - name: yarn install and build
        run: |
          ls -lah
          yarn
          ls -lah
          yarn build
          ls-lah
        env:
          CI: true
